---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Naming/ShortMethodName: # Clarity seems okay for functions like `at`
        enabled: false
      Naming/ShortVariable:   # Mainly for arithmetic functions with vars like $x and $y
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
      Naming/ConstantNamingConventions:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/
