language: php

os:
  - linux

git:
  depth: 1

php:
  - '5.6'
  - '7.0'
  - '7.1'

matrix:
  fast_finish: true

sudo: false

install:
  - travis_retry composer install --no-interaction

before_script:
  - mkdir -p build/logs
  - ls -al

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - ./vendor/bin/test-reporter

branches:
  only: master

cache:
  directories:
  - vendor
  - $HOME/.cache/composer
